environment:
  matrix:
    - ARCH: "x86"
    - ARCH: "x64"

build_script:
  - ./build_windows.bat

artifacts:
  - path: 'build\x64_world.dll'
    name: x64_WORLD
  - path: 'build\x86_world.dll'
    name: x86_WORLD